name: task-all

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    name: pytest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
        - name: Install dependencies
          run: |
            pip install -r ./requirements.txt
        - name: Run test
          run: pytest test.py > report.html
        - uses: actions/upload-artifact@v4
          with:
            name: report-${{ matrix.os }}-${{ matrix.python-version }}
            path: report.html
        - name: Run processing test
          run: pytest test_proc.py > proc-report.html
        - uses: actions/upload-artifact@v4
          with:
            name: proc-report-${{ matrix.os }}-${{ matrix.python-version }}
            path: proc-report.html
